name: CI

on: ['push', 'pull_request']

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true


jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      
      - name: Download modules
        run: go mod download

      - name: go-test
        shell: bash
        run: make test

      - name: go-coverage
        shell: bash
        run : |-
          OUTPUT="$(make test-coverage)"
          TOTAL="$(echo $OUTPUT | awk 'END{print $NF}')"
          echo "::group::Coverage ($TOTAL%)"
          echo "${OUTPUT}"
          echo "::endgroup::"